spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    username: "${DB_USR:postgres}"
    password: "${DB_PSW:postgres}"
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ggop}"
  liquibase:
    change-log: classpath:changelog/changelog.xml


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG